/* Generated by Yosys 0.65+51 (git sha1 5c6de0446, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module axi_prng_top(aclk, aresetn, s_axi_awaddr, s_axi_awvalid, s_axi_awready, s_axi_wdata, s_axi_wstrb, s_axi_wvalid, s_axi_wready, s_axi_bresp, s_axi_bvalid, s_axi_bready, s_axi_araddr, s_axi_arvalid, s_axi_arready, s_axi_rdata, s_axi_rresp, s_axi_rvalid, s_axi_rready);
  input aclk;
  wire aclk;
  input aresetn;
  wire aresetn;
  input [31:0] s_axi_awaddr;
  wire [31:0] s_axi_awaddr;
  input s_axi_awvalid;
  wire s_axi_awvalid;
  output s_axi_awready;
  wire s_axi_awready;
  input [31:0] s_axi_wdata;
  wire [31:0] s_axi_wdata;
  input [3:0] s_axi_wstrb;
  wire [3:0] s_axi_wstrb;
  input s_axi_wvalid;
  wire s_axi_wvalid;
  output s_axi_wready;
  wire s_axi_wready;
  output [1:0] s_axi_bresp;
  wire [1:0] s_axi_bresp;
  output s_axi_bvalid;
  wire s_axi_bvalid;
  input s_axi_bready;
  wire s_axi_bready;
  input [31:0] s_axi_araddr;
  wire [31:0] s_axi_araddr;
  input s_axi_arvalid;
  wire s_axi_arvalid;
  output s_axi_arready;
  wire s_axi_arready;
  output [31:0] s_axi_rdata;
  wire [31:0] s_axi_rdata;
  output [1:0] s_axi_rresp;
  wire [1:0] s_axi_rresp;
  output s_axi_rvalid;
  wire s_axi_rvalid;
  input s_axi_rready;
  wire s_axi_rready;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire \u_axi_slave.ctrl_enable ;
  wire \u_axi_slave.ctrl_load_seed ;
  wire [3:0] \u_axi_slave.rand_out ;
  wire [3:0] \u_axi_slave.seed_reg ;
  sky130_fd_sc_hd__clkinv_1 _093_ (
    .A(\u_axi_slave.seed_reg [3]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _094_ (
    .A(\u_axi_slave.seed_reg [1]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _095_ (
    .A(\u_axi_slave.seed_reg [2]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _096_ (
    .A(\u_axi_slave.rand_out [1]),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _097_ (
    .A(s_axi_rready),
    .Y(_036_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _098_ (
    .A(aresetn),
    .SLEEP(\u_axi_slave.ctrl_load_seed ),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2b_1 _099_ (
    .A_N(\u_axi_slave.ctrl_load_seed ),
    .B(aresetn),
    .Y(_038_)
  );
  sky130_fd_sc_hd__xnor2_1 _100_ (
    .A(\u_axi_slave.rand_out [0]),
    .B(\u_axi_slave.rand_out [3]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor3_1 _101_ (
    .A(\u_axi_slave.seed_reg [3]),
    .B(\u_axi_slave.seed_reg [1]),
    .C(\u_axi_slave.seed_reg [2]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__o21ai_0 _102_ (
    .A1(\u_axi_slave.seed_reg [0]),
    .A2(_040_),
    .B1(_038_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o21ai_0 _103_ (
    .A1(_038_),
    .A2(_039_),
    .B1(_041_),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand2_1 _104_ (
    .A(\u_axi_slave.rand_out [1]),
    .B(_037_),
    .Y(_042_)
  );
  sky130_fd_sc_hd__o21ai_0 _105_ (
    .A1(_034_),
    .A2(_037_),
    .B1(_042_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_1 _106_ (
    .A(\u_axi_slave.rand_out [0]),
    .B(_037_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__o21ai_0 _107_ (
    .A1(_033_),
    .A2(_037_),
    .B1(_043_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor3_1 _108_ (
    .A(s_axi_awaddr[2]),
    .B(s_axi_awaddr[0]),
    .C(s_axi_awaddr[1]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor4bb_1 _109_ (
    .A(s_axi_bvalid),
    .B(s_axi_awready),
    .C_N(s_axi_wvalid),
    .D_N(s_axi_awvalid),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand3_1 _110_ (
    .A(s_axi_awaddr[3]),
    .B(_044_),
    .C(_045_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o21ai_0 _111_ (
    .A1(s_axi_wdata[2]),
    .A2(_046_),
    .B1(aresetn),
    .Y(_047_)
  );
  sky130_fd_sc_hd__a21oi_1 _112_ (
    .A1(_034_),
    .A2(_046_),
    .B1(_047_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o21ai_0 _113_ (
    .A1(s_axi_wdata[1]),
    .A2(_046_),
    .B1(aresetn),
    .Y(_048_)
  );
  sky130_fd_sc_hd__a21oi_1 _114_ (
    .A1(_033_),
    .A2(_046_),
    .B1(_048_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__mux2i_1 _115_ (
    .A0(s_axi_wdata[0]),
    .A1(\u_axi_slave.seed_reg [0]),
    .S(_046_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(aresetn),
    .B(_049_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor3b_1 _117_ (
    .A(s_axi_rvalid),
    .B(s_axi_arready),
    .C_N(s_axi_arvalid),
    .Y(_050_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _118_ (
    .A(s_axi_araddr[3]),
    .SLEEP(s_axi_araddr[2]),
    .X(_051_)
  );
  sky130_fd_sc_hd__nand2_1 _119_ (
    .A(\u_axi_slave.seed_reg [2]),
    .B(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _120_ (
    .A(s_axi_araddr[2]),
    .SLEEP(s_axi_araddr[3]),
    .X(_053_)
  );
  sky130_fd_sc_hd__nand2_1 _121_ (
    .A(\u_axi_slave.rand_out [2]),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__o21ai_0 _122_ (
    .A1(s_axi_rdata[2]),
    .A2(_050_),
    .B1(aresetn),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a31oi_1 _123_ (
    .A1(_050_),
    .A2(_052_),
    .A3(_054_),
    .B1(_055_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__and2_0 _124_ (
    .A(aresetn),
    .B(_050_),
    .X(_009_)
  );
  sky130_fd_sc_hd__o21ai_0 _125_ (
    .A1(s_axi_rdata[1]),
    .A2(_050_),
    .B1(aresetn),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor2_1 _126_ (
    .A(s_axi_araddr[2]),
    .B(\u_axi_slave.ctrl_load_seed ),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a211o_1 _127_ (
    .A1(_035_),
    .A2(s_axi_araddr[2]),
    .B1(s_axi_araddr[3]),
    .C1(_057_),
    .X(_058_)
  );
  sky130_fd_sc_hd__nand2_1 _128_ (
    .A(\u_axi_slave.seed_reg [1]),
    .B(_051_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a31oi_1 _129_ (
    .A1(_050_),
    .A2(_058_),
    .A3(_059_),
    .B1(_056_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _130_ (
    .A0(\u_axi_slave.ctrl_enable ),
    .A1(\u_axi_slave.rand_out [0]),
    .S(_053_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2i_1 _131_ (
    .A0(_060_),
    .A1(\u_axi_slave.seed_reg [0]),
    .S(_051_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__o21ai_0 _132_ (
    .A1(s_axi_rdata[0]),
    .A2(_050_),
    .B1(aresetn),
    .Y(_062_)
  );
  sky130_fd_sc_hd__a21oi_1 _133_ (
    .A1(_050_),
    .A2(_061_),
    .B1(_062_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _134_ (
    .A(s_axi_araddr[0]),
    .B(s_axi_araddr[1]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__o21ai_0 _135_ (
    .A1(s_axi_rresp[1]),
    .A2(_050_),
    .B1(aresetn),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _136_ (
    .A1(_050_),
    .A2(_021_),
    .B1(_022_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a31o_1 _137_ (
    .A1(aresetn),
    .A2(s_axi_rvalid),
    .A3(_036_),
    .B1(_009_),
    .X(_016_)
  );
  sky130_fd_sc_hd__and2_0 _138_ (
    .A(aresetn),
    .B(_045_),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _139_ (
    .A(aresetn),
    .B(s_axi_bvalid),
    .Y(_023_)
  );
  sky130_fd_sc_hd__o21bai_1 _140_ (
    .A1(s_axi_bready),
    .A2(_023_),
    .B1_N(_010_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__and3b_1 _141_ (
    .A_N(s_axi_awaddr[3]),
    .B(_044_),
    .C(_045_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2i_1 _142_ (
    .A0(\u_axi_slave.ctrl_enable ),
    .A1(s_axi_wdata[0]),
    .S(_024_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _143_ (
    .A(aresetn),
    .SLEEP(_025_),
    .X(_013_)
  );
  sky130_fd_sc_hd__and3_1 _144_ (
    .A(s_axi_wdata[1]),
    .B(aresetn),
    .C(_024_),
    .X(_014_)
  );
  sky130_fd_sc_hd__nand2_1 _145_ (
    .A(\u_axi_slave.rand_out [2]),
    .B(_037_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o21ai_0 _146_ (
    .A1(_032_),
    .A2(_037_),
    .B1(_026_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _147_ (
    .A(\u_axi_slave.ctrl_enable ),
    .SLEEP(_038_),
    .X(_000_)
  );
  sky130_fd_sc_hd__o21ai_0 _148_ (
    .A1(s_axi_bresp[1]),
    .A2(_045_),
    .B1(aresetn),
    .Y(_027_)
  );
  sky130_fd_sc_hd__a21oi_1 _149_ (
    .A1(_044_),
    .A2(_045_),
    .B1(_027_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand2_1 _150_ (
    .A(\u_axi_slave.seed_reg [3]),
    .B(_051_),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _151_ (
    .A(\u_axi_slave.rand_out [3]),
    .B(_053_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__o21ai_0 _152_ (
    .A1(s_axi_rdata[3]),
    .A2(_050_),
    .B1(aresetn),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a31oi_1 _153_ (
    .A1(_050_),
    .A2(_028_),
    .A3(_029_),
    .B1(_030_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__o21ai_0 _154_ (
    .A1(s_axi_wdata[3]),
    .A2(_046_),
    .B1(aresetn),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a21oi_1 _155_ (
    .A1(_032_),
    .A2(_046_),
    .B1(_031_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__dfxtp_1 _156_ (
    .CLK(aclk),
    .D(_006_),
    .Q(s_axi_rdata[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _157_ (
    .CLK(aclk),
    .D(_005_),
    .Q(s_axi_rdata[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _158_ (
    .CLK(aclk),
    .D(_004_),
    .Q(s_axi_rdata[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _159_ (
    .CLK(aclk),
    .D(_007_),
    .Q(s_axi_rdata[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _160_ (
    .CLK(aclk),
    .D(_017_),
    .DE(_000_),
    .Q(\u_axi_slave.rand_out [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _161_ (
    .CLK(aclk),
    .D(_018_),
    .DE(_000_),
    .Q(\u_axi_slave.rand_out [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _162_ (
    .CLK(aclk),
    .D(_019_),
    .DE(_000_),
    .Q(\u_axi_slave.rand_out [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _163_ (
    .CLK(aclk),
    .D(_020_),
    .DE(_000_),
    .Q(\u_axi_slave.rand_out [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _164_ (
    .CLK(aclk),
    .D(_003_),
    .Q(\u_axi_slave.seed_reg [0])
  );
  sky130_fd_sc_hd__dfxtp_1 _165_ (
    .CLK(aclk),
    .D(_002_),
    .Q(\u_axi_slave.seed_reg [1])
  );
  sky130_fd_sc_hd__dfxtp_1 _166_ (
    .CLK(aclk),
    .D(_001_),
    .Q(\u_axi_slave.seed_reg [2])
  );
  sky130_fd_sc_hd__dfxtp_1 _167_ (
    .CLK(aclk),
    .D(_008_),
    .Q(\u_axi_slave.seed_reg [3])
  );
  sky130_fd_sc_hd__dfxtp_1 _168_ (
    .CLK(aclk),
    .D(_010_),
    .Q(s_axi_awready)
  );
  sky130_fd_sc_hd__dfxtp_1 _169_ (
    .CLK(aclk),
    .D(_012_),
    .Q(s_axi_bvalid)
  );
  sky130_fd_sc_hd__dfxtp_1 _170_ (
    .CLK(aclk),
    .D(_013_),
    .Q(\u_axi_slave.ctrl_enable )
  );
  sky130_fd_sc_hd__dfxtp_1 _171_ (
    .CLK(aclk),
    .D(_014_),
    .Q(\u_axi_slave.ctrl_load_seed )
  );
  sky130_fd_sc_hd__dfxtp_1 _172_ (
    .CLK(aclk),
    .D(_011_),
    .Q(s_axi_bresp[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _173_ (
    .CLK(aclk),
    .D(_009_),
    .Q(s_axi_arready)
  );
  sky130_fd_sc_hd__dfxtp_1 _174_ (
    .CLK(aclk),
    .D(_016_),
    .Q(s_axi_rvalid)
  );
  sky130_fd_sc_hd__dfxtp_1 _175_ (
    .CLK(aclk),
    .D(_015_),
    .Q(s_axi_rresp[1])
  );
  sky130_fd_sc_hd__conb_1 _176_ (
    .LO(_063_)
  );
  sky130_fd_sc_hd__conb_1 _177_ (
    .LO(_064_)
  );
  sky130_fd_sc_hd__conb_1 _178_ (
    .LO(_065_)
  );
  sky130_fd_sc_hd__conb_1 _179_ (
    .LO(_066_)
  );
  sky130_fd_sc_hd__conb_1 _180_ (
    .LO(_067_)
  );
  sky130_fd_sc_hd__conb_1 _181_ (
    .LO(_068_)
  );
  sky130_fd_sc_hd__conb_1 _182_ (
    .LO(_069_)
  );
  sky130_fd_sc_hd__conb_1 _183_ (
    .LO(_070_)
  );
  sky130_fd_sc_hd__conb_1 _184_ (
    .LO(_071_)
  );
  sky130_fd_sc_hd__conb_1 _185_ (
    .LO(_072_)
  );
  sky130_fd_sc_hd__conb_1 _186_ (
    .LO(_073_)
  );
  sky130_fd_sc_hd__conb_1 _187_ (
    .LO(_074_)
  );
  sky130_fd_sc_hd__conb_1 _188_ (
    .LO(_075_)
  );
  sky130_fd_sc_hd__conb_1 _189_ (
    .LO(_076_)
  );
  sky130_fd_sc_hd__conb_1 _190_ (
    .LO(_077_)
  );
  sky130_fd_sc_hd__conb_1 _191_ (
    .LO(_078_)
  );
  sky130_fd_sc_hd__conb_1 _192_ (
    .LO(_079_)
  );
  sky130_fd_sc_hd__conb_1 _193_ (
    .LO(_080_)
  );
  sky130_fd_sc_hd__conb_1 _194_ (
    .LO(_081_)
  );
  sky130_fd_sc_hd__conb_1 _195_ (
    .LO(_082_)
  );
  sky130_fd_sc_hd__conb_1 _196_ (
    .LO(_083_)
  );
  sky130_fd_sc_hd__conb_1 _197_ (
    .LO(_084_)
  );
  sky130_fd_sc_hd__conb_1 _198_ (
    .LO(_085_)
  );
  sky130_fd_sc_hd__conb_1 _199_ (
    .LO(_086_)
  );
  sky130_fd_sc_hd__conb_1 _200_ (
    .LO(_087_)
  );
  sky130_fd_sc_hd__conb_1 _201_ (
    .LO(_088_)
  );
  sky130_fd_sc_hd__conb_1 _202_ (
    .LO(_089_)
  );
  sky130_fd_sc_hd__conb_1 _203_ (
    .LO(_090_)
  );
  sky130_fd_sc_hd__conb_1 _204_ (
    .LO(_091_)
  );
  sky130_fd_sc_hd__conb_1 _205_ (
    .LO(_092_)
  );
  assign s_axi_rresp[0] = _063_;
  assign s_axi_rdata[31:4] = { _091_, _090_, _089_, _088_, _087_, _086_, _085_, _084_, _083_, _082_, _081_, _080_, _079_, _078_, _077_, _076_, _075_, _074_, _073_, _072_, _071_, _070_, _069_, _068_, _067_, _066_, _065_, _064_ };
  assign s_axi_bresp[0] = _092_;
  assign s_axi_wready = s_axi_awready;
endmodule